# Generated by Django 3.2.9 on 2022-07-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmrdetail',
            name='user_profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
