# Generated by Django 3.2.9 on 2021-12-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmrdetail',
            name='bmr_entered',
            field=models.BooleanField(default=False),
        ),
    ]
