# Generated by Django 3.2.9 on 2021-11-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmrdetail',
            name='user',
        ),
    ]
