# Generated by Django 3.2.9 on 2021-12-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0002_bmrdetail_bmr_entered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmrdetail',
            name='bmr_entered',
        ),
    ]
