# Generated by Django 3.2.9 on 2022-01-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0003_remove_bmrdetail_bmr_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmrdetail',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1),
        ),
    ]
