# Generated by Django 4.0 on 2022-01-03 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0007_alter_fooditem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='date_added',
            field=models.DateField(default=datetime.date(2022, 1, 3), verbose_name=datetime.date(2022, 1, 3)),
        ),
    ]
