# Generated by Django 4.0 on 2022-01-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0008_fooditem_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='date_added',
        ),
    ]
