# Generated by Django 4.0 on 2022-01-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0009_remove_fooditem_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmrdetail',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bmrdetail',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
