# Generated by Django 4.0 on 2022-01-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0010_alter_bmrdetail_height_alter_bmrdetail_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmrdetail',
            name='bmr',
            field=models.IntegerField(default=0),
        ),
    ]
