# Generated by Django 4.0 on 2022-01-06 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0011_alter_bmrdetail_bmr'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='date_added',
            field=models.DateField(default=datetime.date(2022, 1, 6)),
        ),
    ]
