# Generated by Django 4.0 on 2022-01-06 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0012_fooditem_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 1, 6, 14, 55, 14, 547331, tzinfo=utc)),
        ),
    ]
